# version format
version: 1.0.0

branches:
  only:
  - master



build_script:
  - cd Packaging
  - build.bat

artifacts:
  - path: Packaging\Package\*.nupkg
  - path: Packaging\Package\*.zip
 
 
#deploy:
#  provider: NuGet
#  server:
#  api_key:
#    secure: 
#  artifact: /.*\.nupkg/